Skill.destroy_all

Skill.create(skill: "Ruby")
Skill.create(skill: "JavaScript")
Skill.create(skill: "HTML & CSS")
Skill.create(skill: "Python")
Skill.create(skill: "Database")
Skill.create(skill: "Consulting")
Skill.create(skill: "Accounting")
Skill.create(skill: "Design")
Skill.create(skill: "Sales")
Skill.create(skill: "Fullstack")
Skill.create(skill: "React")
Skill.create(skill: "Legal")
Skill.create(skill: "C++")
